In [1]:
!pip install google-play-scraper

Collecting google-play-scraper
  Downloading google_play_scraper-1.2.7-py3-none-any.whl.metadata (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.2/50.2 kB 2.2 MB/s eta 0:00:00
Downloading google_play_scraper-1.2.7-py3-none-any.whl (28 kB)
Installing collected packages: google-play-scraper
Successfully installed google-play-scraper-1.2.7

In [2]:
from google_play_scraper import app

result = app(
    'com.bca.mybca.omni.android',
    lang='en',
    country='id'
)

In [3]:
result

{'title': 'myBCA: BCA Banking Apps',
 'description': 'From open BCA account online, transfer money online, paying bills, to managing investments — everything is accessible from just one app. myBCA is here to simplify your digital banking needs all in one place. With just one BCA ID, your financial transactions can be done anytime, anywhere.\r\nMain Features:\r\n1. Domestic & International Transfers\r\nSend money to fellow BCA users, other banks, virtual accounts, or top up e-wallets like OVO, DANA, and more. Easily transfer foreign currencies with competitive exchange rates. Perfect for personal or business transfers — a powerful foreign exchange app.\r\n2. Complete Bill & Daily Payment Services\r\nPay electricity, water, internet, vehicle tax, education fees, and even credit card installments — all from within the app.\r\n3. Practical QRIS & QRIS Tap Payments\r\nMake payments by scanning QRIS codes or tapping your phone at any EDC that supports QRIS Tap. Works across Indonesia, Thailand, Singapore, and Malaysia.\r\n4. Cardless Cash Withdrawals\r\nForgot your wallet? No problem. Use the cardless feature in myBCA to deposit or withdraw cash at any BCA ATM.\r\n5. Fast & Secure Login Anywhere\r\nAccess the app quickly and securely using fingerprint or Face ID — no need to enter your PIN repeatedly.\r\n6. Online Foreign Currency Savings\r\nBuy and save in foreign currencies with the Poket Valas feature. Choose from up to 17 currencies, available 24/7 with great exchange rates. Ideal for business, travel, or long-term investing. Use your BCA Mastercard debit card abroad with no conversion hassle.\r\n7. Curated Investments from Rp10,000\r\nStart investing from just Rp10,000 with access to mutual funds and bonds. Safe, curated, and built around your investment goals — all accessible via mobile. It’s your digital account opening app for investing.\r\n8. Financial Diary & Transaction History\r\nTrack your daily expenses using Financial Diary and view your transaction history all the way back to 2016 — across all accounts in one dashboard.\r\n9. Multi-Platform Access\r\nAccess myBCA via the mobile app, web browser, or Wear OS devices. Flexible and secure across devices.\r\n10. Exclusive Features for Priority Customers\r\nEnjoy exclusive offers and services for Priority and Solitaire customers — including lifestyle, health, and travel benefits.\r\n\r\nAccess myBCA using a Wear OS smartwatch to check account balance, view transaction history, perform cardless transactions, use QRIS, and use NFC Pay.\r\nFor the security and integrity of your data, the myBCA app cannot be used on devices that have been rooted, hooked, running on an emulator, or have unauthorized system modifications.\r\nDownload myBCA Now!\r\n\r\n* Download myBCA and enjoy seamless banking right from your fingertips\r\n* Perfect for those looking to open BCA account online, save in foreign currencies, invest, or just pay electricity bills from home\r\n* All your transactions — one app. Faster, safer, and hassle-free!\r\n#myBCA #OpenBankAccountOnlineFree #TransferUang #QRIS #TopUpEwallet #ForeignExchangeApp #OnlineInvestment #DigitalBanking #BankNewAccountOpeningOnline #myBCAPayLater',
 'descriptionHTML': 'From open BCA account online, transfer money online, paying bills, to managing investments — everything is accessible from just one app. myBCA is here to simplify your digital banking needs all in one place. With just one BCA ID, your financial transactions can be done anytime, anywhere.<br>Main Features:<br>1. Domestic &amp; International Transfers<br>Send money to fellow BCA users, other banks, virtual accounts, or top up e-wallets like OVO, DANA, and more. Easily transfer foreign currencies with competitive exchange rates. Perfect for personal or business transfers — a powerful foreign exchange app.<br>2. Complete Bill &amp; Daily Payment Services<br>Pay electricity, water, internet, vehicle tax, education fees, and even credit card installments — all from within the app.<br>3. Practical QRIS &amp; QRIS Tap Payments<br>Make payments by scanning QRIS codes or tapping your phone at any EDC that supports QRIS Tap. Works across Indonesia, Thailand, Singapore, and Malaysia.<br>4. Cardless Cash Withdrawals<br>Forgot your wallet? No problem. Use the cardless feature in myBCA to deposit or withdraw cash at any BCA ATM.<br>5. Fast &amp; Secure Login Anywhere<br>Access the app quickly and securely using fingerprint or Face ID — no need to enter your PIN repeatedly.<br>6. Online Foreign Currency Savings<br>Buy and save in foreign currencies with the Poket Valas feature. Choose from up to 17 currencies, available 24/7 with great exchange rates. Ideal for business, travel, or long-term investing. Use your BCA Mastercard debit card abroad with no conversion hassle.<br>7. Curated Investments from Rp10,000<br>Start investing from just Rp10,000 with access to mutual funds and bonds. Safe, curated, and built around your investment goals — all accessible via mobile. It’s your digital account opening app for investing.<br>8. Financial Diary &amp; Transaction History<br>Track your daily expenses using Financial Diary and view your transaction history all the way back to 2016 — across all accounts in one dashboard.<br>9. Multi-Platform Access<br>Access myBCA via the mobile app, web browser, or Wear OS devices. Flexible and secure across devices.<br>10. Exclusive Features for Priority Customers<br>Enjoy exclusive offers and services for Priority and Solitaire customers — including lifestyle, health, and travel benefits.<br><br>Access myBCA using a Wear OS smartwatch to check account balance, view transaction history, perform cardless transactions, use QRIS, and use NFC Pay.<br>For the security and integrity of your data, the myBCA app cannot be used on devices that have been rooted, hooked, running on an emulator, or have unauthorized system modifications.<br>Download myBCA Now!<br><br>* Download myBCA and enjoy seamless banking right from your fingertips<br>* Perfect for those looking to open BCA account online, save in foreign currencies, invest, or just pay electricity bills from home<br>* All your transactions — one app. Faster, safer, and hassle-free!<br>#myBCA #OpenBankAccountOnlineFree #TransferUang #QRIS #TopUpEwallet #ForeignExchangeApp #OnlineInvestment #DigitalBanking #BankNewAccountOpeningOnline #myBCAPayLater',
 'summary': 'Seamless access for daily transactions and investments — all in one app.',
 'installs': '10,000,000+',
 'minInstalls': 10000000,
 'realInstalls': 44967990,
 'score': 3.8878431,
 'ratings': 90689,
 'reviews': 40207,
 'histogram': [18755, 4035, 4658, 4406, 58829],
 'price': 0,
 'free': True,
 'currency': 'IDR',
 'sale': False,
 'saleTime': None,
 'originalPrice': None,
 'saleText': None,
 'offersIAP': False,
 'inAppProductPrice': None,
 'developer': 'PT Bank Central Asia Tbk.',
 'developerId': '9162366183828083338',
 'developerEmail': 'halobca@bca.co.id',
 'developerWebsite': 'https://www.bca.co.id/',
 'developerAddress': None,
 'privacyPolicy': 'https://www.bca.co.id/informasi/Kebijakan',
 'genre': 'Finance',
 'genreId': 'FINANCE',
 'categories': [{'name': 'Finance', 'id': 'FINANCE'}],
 'icon': 'https://play-lh.googleusercontent.com/ckrnc0pzN0oZgSaMQMnOYrICdBLwFTuI17MlTUp9ftyZPJ-m4K1pA3_Dz1B-1dCFVZbv',
 'headerImage': 'https://play-lh.googleusercontent.com/HMCd9sh-UciOorat2uGTQoyaVqV7JQieoVjquJgcdecvESsCnsNQU-uTv-rl3dwar38',
 'screenshots': ['https://play-lh.googleusercontent.com/udTleTX9Xf0AJjr6LAYFBISZsF2A4UE-HltbatUZRisx2La2XOTu0YtNbHctib3yajv69mabai7v9lM3o551EQ',
  'https://play-lh.googleusercontent.com/5E4GvgxsyWg6KEtfm88VrCYtJ4GP6Y7qiZOl11SUtbBWkx94be_1gIBWAPAgEs9b6AUwoK2r6EV7YrWGDg_7pQ',
  'https://play-lh.googleusercontent.com/slc6ZOQkMBIWQf21Unn-pJRDvWcoemGb0dHDc2rrUNG0uJXUFv8nlCkxM4AzFbOwreGfL6OnvxvH6B5GS2ZAVzU',
  'https://play-lh.googleusercontent.com/RL33uiA97NtJYSKQDo0LbRicP0EOJmQU9r1s4r9NdxFUt3CO56aGAUXJBOoGY_rYLbigl4_K8TXftDEXHwYOBQ',
  'https://play-lh.googleusercontent.com/dquGCRR2R4uHt47JnTi2zMcxxpUqreQrdwp0UdrhcuGd-_k5-8or9Z-8OuxPxKtxUPjfsPBCqUluzEiYujRD',
  'https://play-lh.googleusercontent.com/ZVhlmY8uJtaC-xc5QNSjLyGn-qqDdkqaLhjJJiZoynmF7rMcZGrr4d0NmP9DKXKnGfZnztFYrzuxZRopBLZ2Xw',
  'https://play-lh.googleusercontent.com/JfiQdYQOirYqxHaVbFZWf981AuENoQEpMS0SUZywM-xo5yJtRZNwZ7gQdTOGpqywTeUnvuiJVFcZyKECa2n2IQ',
  'https://play-lh.googleusercontent.com/Z-fB40lpvmscNaEgcON1k8aEedbx1vz4IoNbXzrqDUW7_9O0cDYr4XLqHz_zGMkBc5I5hIcVybio1DeKF2wdTg',
  'https://play-lh.googleusercontent.com/b27bqNC3E-ww8QZIGVqg2aH5lQJRaWklOwsRE4j4FViN7DZDZYB7jL4-o_-iDW2UqcFTCfMbXIBCnOHXxUJsSA',
  'https://play-lh.googleusercontent.com/MOV8ngtEyv6UwJrVRgby0o4ckwwAOxhMTOd-WoBcT06XT9ABiIrjowjlWuu1QF_ghA3CJs5UTnG_ZscKj2Gef7s',
  'https://play-lh.googleusercontent.com/OsmOQa5lvWc5jLNkEx5BOFLRp8Ac_HTSShmznMG1O1AGOm8qtc6yeTRqIK-SwZEUt5dWkY5C6b_V_tq7GrdYuw',
  'https://play-lh.googleusercontent.com/9MLLrq7PmCKyoV0qeODlXgEvtDRegN-VdA--ssvrJfAoPgVMRBG48OAvGjmwPGz0JUsckFZe-84pqZRF1E0v',
  'https://play-lh.googleusercontent.com/e2m_eTl37RaqxFUTquPDlmVgNXdakf6_lMi5-cq-d2E6yxHFQUQ2XdDyqFBif7UN_V3w9f4iuGDAxize-B5_3A',
  'https://play-lh.googleusercontent.com/g2GxqcPSF7kqzEQOLPlIRWgIZEN6DVRzpN7I6SHE0c_BGia2HXlXf5velCkFyJT6I42qaJYF_QYuWDl7Dv6AqIA'],
 'video': 'https://www.youtube.com/embed/n5_wCF5UB3U?vq=large&rel=0&autohide=1&showinfo=0',
 'videoImage': 'https://play-lh.googleusercontent.com/HMCd9sh-UciOorat2uGTQoyaVqV7JQieoVjquJgcdecvESsCnsNQU-uTv-rl3dwar38',
 'contentRating': 'Rated for 3+',
 'contentRatingDescription': None,
 'adSupported': False,
 'containsAds': False,
 'released': 'May 3, 2021',
 'lastUpdatedOn': 'Apr 14, 2026',
 'updated': 1776161398,
 'version': 'Varies with device',
 'comments': [],
 'appId': 'com.bca.mybca.omni.android',
 'url': 'https://play.google.com/store/apps/details?id=com.bca.mybca.omni.android&hl=en&gl=id'}

In [4]:
from google_play_scraper import Sort, reviews

result, continuation_token = reviews(
    'com.bca.mybca.omni.android',
    lang='en',
    country='id',
    sort=Sort.NEWEST,
    count=5,
    filter_score_with=None
)

result, _ = reviews(
    'com.bca.mybca.omni.android',
    continuation_token=continuation_token
)

In [5]:
result

[{'reviewId': '0718dbe2-20a9-41b1-b8ea-7f242653b41b',
  'userName': 'Alice Akira',
  'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocIs6bk9-GC7QruYF26Iy1TrpVNEwihTVReHfX9HxgzYhIUO6w=mo',
  'content': 'jujur, opsi forgot/reset password nya ribet, harus telpon cs dan ga bisa pake verifikasi data aja gitu? pengecekan akun juga ga pake nomor hp, cuma by email / account number / atm, jadi pas mau registrasi pake nomor yg sama itu masih lolos, email yg sama ga bisa tapi klo pake email lain masih lolos, ga bisa nya pas udah isi no rek, jadi terpaksa uninstall karena males musti telpon cs buat reset password',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': None,
  'at': datetime.datetime(2026, 4, 13, 13, 35, 38),
  'replyContent': 'Mohon maaf atas ketidaknyamanan Bapak/Ibu, untuk kendala tersebut mohon dapat menginformasikan detail gambar kendala yang dialami ke layanan X (Twitter) @HaloBCA atau Email halobca@bca.co.id atau Halo BCA Chat: akses melalui www.bca.co.id atau WhatsApp BCA 08111500998 agar dibantu lebih lanjut.',
  'repliedAt': datetime.datetime(2026, 4, 13, 14, 9, 24),
  'appVersion': None},
 {'reviewId': '6a65e129-ded0-4ac3-9f7f-0520cdb75d5b',
  'userName': 'Abel Fadhlurrahman',
  'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjVjIHbO3AvEXOlQQh4DsE34QaQVrm7MV8JqvJ-X_dg9Cdy6P8UQ',
  'content': 'cuma karena ga ada transaksi keluar 3 bulan nomer di block ga bisa masuk..',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '2.15.1',
  'at': datetime.datetime(2026, 4, 13, 12, 53, 3),
  'replyContent': 'Mohon maaf atas ketidaknyamanan Bapak/Ibu, untuk kendala tersebut mohon dapat menginformasikan detail gambar kendala yang dialami ke layanan X (Twitter) @HaloBCA atau Email halobca@bca.co.id atau Halo BCA Chat: akses melalui www.bca.co.id atau WhatsApp BCA 08111500998 agar dibantu lebih lanjut.',
  'repliedAt': datetime.datetime(2026, 4, 13, 14, 5, 10),
  'appVersion': '2.15.1'},
 {'reviewId': 'c03b140a-5a14-47ce-959c-9056a5d7373a',
  'userName': 'merina isnaning',
  'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocKMZsooIHhjQ873n64Zu0wdVJUVjuIe4LLaMzCummFs0iN-LQ=mo',
  'content': 'mybca kenapa ya hari ini?? mau transfer loadingnya lama sekali, padahal ke sesama bca. jangan bilang karena jaringan ya, karena saya pindah ke aplikasi m-banking lain bisa dan lancar. mau isi ulang flazz juga loadingnya lama setengah mati. udah update ke versi paling baru padahal. ga jadi saya kasi predikat aplikasi m-banking paling baik kalo performanya kayak gini. menurun.',
  'score': 2,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '2.15.1',
  'at': datetime.datetime(2026, 4, 13, 8, 56, 58),
  'replyContent': 'Mohon maaf atas ketidaknyamanannya Bapak/Ibu. Saat ini tdk ada kendala myBCA. Mohon pastikan koneksi jaringan stabil saat ingin menggunakan aplikasi myBCA dan ruang penyimpanan di perangkat yang dipergunakan mencukupi. Kami sarankan juga restart HP terlebih dahulu dan Bapak/Ibu dapat mencoba mengakses kembali secara berkala.\n',
  'repliedAt': datetime.datetime(2026, 4, 13, 9, 13, 16),
  'appVersion': '2.15.1'},
 {'reviewId': '3c0b3212-2be0-4954-a7bd-2d3f34ca4519',
  'userName': 'Imam Sibro Muhlisi',
  'userImage': 'https://play-lh.googleusercontent.com/a/ACg8ocKAcHdZ-OJSyEKXlHcf5KGbitavc1wS20jgALA-UJRegKgI-Q=mo',
  'content': 'tambah sini tambah lemot koneksinya',
  'score': 1,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '2.15.1',
  'at': datetime.datetime(2026, 4, 13, 3, 20, 39),
  'replyContent': 'Mohon maaf atas ketidaknyamanannya. Mohon pastikan koneksi jaringan stabil saat ingin menggunakan aplikasi myBCA dan ruang penyimpanan di perangkat yang dipergunakan mencukupi. Kami sarankan juga restart HP terlebih dahulu dan Bapak/Ibu dapat mencoba mengakses kembali secara berkala.',
  'repliedAt': datetime.datetime(2026, 4, 13, 4, 18, 10),
  'appVersion': '2.15.1'},
 {'reviewId': 'ca9426a6-678e-4b53-aa11-934eb88c4ad7',
  'userName': 'Angga Fajar',
  'userImage': 'https://play-lh.googleusercontent.com/a-/ALV-UjV6x9jBkRayn5k2zAucYdErUXSJHxfAtVNexy5rlWp7w4Q4psYi',
  'content': 'This app need Pay QRis with Credit Card..',
  'score': 2,
  'thumbsUpCount': 0,
  'reviewCreatedVersion': '2.15.1',
  'at': datetime.datetime(2026, 4, 12, 23, 48, 11),
  'replyContent': 'Sorry for the inconvenience, Sir/Madam. Your suggestions and reviews will be used as evaluation material for us in the future to develop better applications.',
  'repliedAt': datetime.datetime(2026, 4, 13, 1, 32, 9),
  'appVersion': '2.15.1'}]

In [6]:
from google_play_scraper import reviews, Sort
import pandas as pd

all_reviews = []
continuation_token = None

for i in range(10):
    result, continuation_token = reviews(
        'com.bca.mybca.omni.android',
        lang='id',
        country='id',
        sort=Sort.NEWEST,
        count=2000,
        continuation_token=continuation_token
    )

    all_reviews.extend(result)

    if not continuation_token:
        break

df = pd.DataFrame(all_reviews)

In [7]:
print("Total data:", len(df))
df.head(50)

Total data: 20000

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion
0,8a497600-5a33-47d7-8f2b-3ef8f100bfec,Nyoman Sukiati,https://play-lh.googleusercontent.com/a-/ALV-U...,saya suka apk ini,5,0,2.15.1,2026-04-15 01:58:09,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-15 02:58:33,2.15.1
1,e3093d45-be8b-4075-b994-685b5c15afef,Gho Far,https://play-lh.googleusercontent.com/a-/ALV-U...,"untuk Xpresi biaya admin bulanan mahal banget,...",1,0,None,2026-04-14 23:02:28,"Mohon maaf atas ketidaknyamanannya, ulasan Bap...",2026-04-15 01:17:28,None
2,46178fa7-8535-44ef-b5e7-a6745a4ab678,Puang Ruslan,https://play-lh.googleusercontent.com/a-/ALV-U...,TKS atas aplikasinya,5,0,2.15.1,2026-04-14 19:29:57,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-15 01:12:15,2.15.1
3,56815cc4-a256-4ba9-9895-36995db2e80a,Yessi Alruvi,https://play-lh.googleusercontent.com/a/ACg8oc...,uninstal dulu setelah ada perbaikan baru pake ...,1,0,2.15.1,2026-04-14 18:53:33,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, moh...",2026-04-15 01:17:51,2.15.1
4,a170b56d-38d6-45c3-b4a9-7a8199b6970e,Fazar Oktavian,https://play-lh.googleusercontent.com/a/ACg8oc...,baik,3,0,2.15.1,2026-04-14 18:49:41,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-15 01:12:11,2.15.1
5,b147053e-a953-487c-9826-d00c65777f37,Aldy SF,https://play-lh.googleusercontent.com/a/ACg8oc...,setelah update malah makin lemot my bca nya,3,0,None,2026-04-14 18:45:21,Mohon maaf atas kendala yang Bapak/Ibu alami. ...,2026-04-15 01:11:14,None
6,a3d5c90c-a3a8-4b42-ad1d-62525d005920,Rizal Odoth,https://play-lh.googleusercontent.com/a-/ALV-U...,ewalletnya gak banyak pilihannya cuma ada dana...,4,0,2.15.1,2026-04-14 17:24:50,Mohon maaf atas ketidaknyamanannya. Saran dan ...,2026-04-14 18:30:15,2.15.1
7,0f423af0-12b1-4271-9c7b-27e866a2bc44,saskia ananda,https://play-lh.googleusercontent.com/a-/ALV-U...,tolong dong pihak bca gausa update trs bikin h...,1,0,2.15.1,2026-04-14 16:09:39,"Mohon maaf atas ketidaknyamanannya Bapak/Ibu, ...",2026-04-14 17:23:48,2.15.1
8,72599e2d-2f1a-4b49-943e-8708d342605e,Sri Reski,https://play-lh.googleusercontent.com/a-/ALV-U...,kenapa saldo saya terpotong 25000 tampa ada no...,2,0,2.15.1,2026-04-14 15:17:57,"Mohon maaf atas kendala yang Bapak/Ibu alami, ...",2026-04-14 17:22:30,2.15.1
9,bfd5ab75-d0fe-4d1d-bd67-e091fd9ec30b,Fajri,https://play-lh.googleusercontent.com/a-/ALV-U...,kenapa saya tidak ada kode +62 khusus nomor In...,1,0,2.15.1,2026-04-14 14:43:34,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, saa...",2026-04-14 15:07:15,2.15.1
10,948479c9-0d4c-439a-8861-3bfe16ae36a9,Rohedi 67,https://play-lh.googleusercontent.com/a-/ALV-U...,bagus,5,0,2.15.1,2026-04-14 14:40:24,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 15:06:37,2.15.1
11,53779778-f6f3-456d-97e2-8c8912126349,Coral Reef Tank,https://play-lh.googleusercontent.com/a-/ALV-U...,Kepada pelanggan bca paylater..hati2 menggunak...,1,0,2.15.1,2026-04-14 14:05:58,"Mohon maaf atas kendala yang Bapak/Ibu alami, ...",2026-04-14 15:05:12,2.15.1
12,4e2dcfd1-e687-451a-9a8f-06f36327a903,Sandi1 Sandi1,https://play-lh.googleusercontent.com/a/ACg8oc...,lupa ID nya my BCA lupa imel nya BCA my BCA,5,0,2.15.1,2026-04-14 13:03:36,apabila lupa BCA ID dan email maka bisa mengak...,2026-04-14 13:15:47,2.15.1
13,05ffdc1c-2aa0-41c1-89d5-184e43ef5637,Syaza Ann,https://play-lh.googleusercontent.com/a/ACg8oc...,KALAU APLIKASI BELUM SIAP JANGAN DI LUNCURKAN ...,1,0,None,2026-04-14 12:47:53,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, moh...",2026-04-14 13:15:54,None
14,98983f71-bab8-4c27-bdd7-6745a593106e,Much Iksan Prayitno,https://play-lh.googleusercontent.com/a-/ALV-U...,"udah bisa dibuka,semoga kedepan makin bagus ap...",4,0,2.15.1,2026-04-14 12:04:28,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 13:16:59,2.15.1
15,3bb31397-2242-48c2-b955-e70548ae6b67,Not Name,https://play-lh.googleusercontent.com/a-/ALV-U...,bca.. knp sering TB TB logout akun sendiri?? a...,3,0,2.15.1,2026-04-14 11:02:11,Mohon maaf atas ketidaknyamanannya. Saran dan ...,2026-04-14 11:38:06,2.15.1
16,26bc2c8d-3e9e-431b-9a95-2d2bff9989ba,Bono Sanyoto,https://play-lh.googleusercontent.com/a-/ALV-U...,"verifikasi wajah selalu gagal, mesti lewat vid...",2,0,2.15.1,2026-04-14 10:52:28,"Mohon maaf atas kendala yang Bapak/Ibu alami, ...",2026-04-14 11:37:18,2.15.1
17,541da0af-f95f-4cde-b2cd-483f1b96fa86,Ibnu Wahyudi,https://play-lh.googleusercontent.com/a-/ALV-U...,Bagus,5,0,2.15.1,2026-04-14 09:50:03,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 10:31:05,2.15.1
18,236aabcb-d7c6-4db8-8b87-ec0e7f8d87de,Yanuar Lazuardi,https://play-lh.googleusercontent.com/a-/ALV-U...,min kenapa sqya mau login kode negara di nomor...,1,0,2.15.1,2026-04-14 09:48:57,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, saa...",2026-04-14 10:30:07,2.15.1
19,7116c21e-6e29-4a36-9a73-ac6a88d711f3,Babi Guling,https://play-lh.googleusercontent.com/a/ACg8oc...,bank pelit medit kikir buat naik limit cc,1,0,None,2026-04-14 09:15:49,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2026-04-14 09:41:21,None
20,d3743ae7-10a8-43c7-9c0b-09f9e6934440,Wulan Arpra,https://play-lh.googleusercontent.com/a-/ALV-U...,bagus banget,5,0,2.15.1,2026-04-14 08:31:58,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 09:21:47,2.15.1
21,903a8539-6243-4b42-bc8f-f90e34409547,Imelda Ita,https://play-lh.googleusercontent.com/a/ACg8oc...,stuck di logo my BCA ini kenapa ya,4,0,None,2026-04-14 07:55:38,Mohon maaf atas kendala yang Bapak/Ibu alami. ...,2026-04-14 08:18:01,None
22,323bcfb8-f8df-440c-9d6e-25acc051c5b7,Dede Iskandar,https://play-lh.googleusercontent.com/a/ACg8oc...,sangat puas,5,0,2.15.1,2026-04-14 07:54:23,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 08:17:49,2.15.1
23,79a3506c-56e9-4d05-80c5-6f91af575cf2,Fariadi Johannis,https://play-lh.googleusercontent.com/a/ACg8oc...,aplikasinya kalau update selalu error tolong p...,5,0,None,2026-04-14 07:20:24,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, moh...",2026-04-14 08:17:38,None
24,3dfd51d2-82f4-4f9f-9581-d61736dac0a8,Herkules Andri,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus untuk transaksi,5,0,None,2026-04-14 06:02:02,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 06:45:24,None
25,a9408e72-11d3-4c40-a393-13390ca065f1,ade mulya,https://play-lh.googleusercontent.com/a/ACg8oc...,Kagak Jelas ngabisin pulsa doank,5,0,2.15.1,2026-04-14 06:00:09,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, moh...",2026-04-14 08:19:56,2.15.1
26,0975e3cb-21c0-45c2-8ad6-93bd12cfb641,Roby,https://play-lh.googleusercontent.com/a-/ALV-U...,knapa dah pas gw login trus langsung suruh mas...,2,0,2.6.0,2026-04-14 05:54:38,Mhn maaf atas ketidaknyamanannya Bapak/Ibu. Pe...,2026-04-14 06:45:17,2.6.0
27,4163f110-2977-46d0-9b67-9b4307b62f8b,Mahmur Muhamad,https://play-lh.googleusercontent.com/a/ACg8oc...,sangat senang dengan mybca😘,5,0,2.15.1,2026-04-14 05:24:44,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 06:44:52,2.15.1
28,f1514f65-600b-4baa-970b-5198052cc828,Ferdiansyah Bin Mana,https://play-lh.googleusercontent.com/a/ACg8oc...,"ganti HP aja terblokir, karena otp lambat date...",1,0,2.15.1,2026-04-14 04:59:25,Mhn maaf atas ketidaknyamanannya. Mhn Bpk/Ibu ...,2026-04-14 06:44:04,2.15.1
29,81f027e9-b8e2-4a7b-946c-15c8db7a4891,Wahyu plat-E chennel,https://play-lh.googleusercontent.com/a-/ALV-U...,good job,5,0,2.8.1,2026-04-14 04:45:56,Thank you for the review. We hope that the myB...,2026-04-14 06:43:07,2.8.1
30,bd727315-a641-43ba-ab05-2640bac090e4,Ratu Hera,https://play-lh.googleusercontent.com/a/ACg8oc...,setelah update my bca knp aplikasinya jadi lem...,5,0,2.15.1,2026-04-14 04:02:30,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 04:42:36,2.15.1
31,44aeed15-aa16-4d16-905e-33fd834c8c3f,Akun Aku,https://play-lh.googleusercontent.com/a/ACg8oc...,sayang banget udh pesen kartu ATM dikirim ke r...,2,0,None,2026-04-14 03:45:00,"Mohon maaf atas ketidaknyamanannya, ulasan Bap...",2026-04-14 04:41:59,None
32,6ae50675-fe44-4794-9b38-18ab98bc800b,Apandi Apandi,https://play-lh.googleusercontent.com/a/ACg8oc...,bagus,5,0,2.15.1,2026-04-14 03:27:08,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 03:47:04,2.15.1
33,341ecffb-210d-42d5-bb8d-afa968b2b249,Putu Darmawan,https://play-lh.googleusercontent.com/a/ACg8oc...,Setelah tidak bisa transaksi. tiba-tiba logout...,1,0,None,2026-04-14 02:37:55,Mhn maaf atas ketidaknyamanannya Bapak/Ibu. Pe...,2026-04-14 02:48:23,None
34,350764d4-8409-48ec-96e8-3b17230fbe72,4_Bayu Aji Saputra Hasibuan_P_IPS (Aji),https://play-lh.googleusercontent.com/a-/ALV-U...,"makin lama makin lemot buat masuk nya, padahal...",1,0,2.15.1,2026-04-14 02:26:57,Mohon maaf atas kendala yang Bapak/Ibu alami. ...,2026-04-14 02:47:55,2.15.1
35,e8a269e7-b45a-47de-b31f-9d43e138c024,Darkum,https://play-lh.googleusercontent.com/a-/ALV-U...,Tolong Diperbaiki Stelh Update Dn Update Yang ...,2,0,None,2026-04-14 02:12:32,Mohon maaf atas kendala yang Bapak/Ibu alami. ...,2026-04-14 02:47:50,None
36,2dd56d68-a9f9-41ac-a698-b0a9fdf86732,Farhan Inayatullah,https://play-lh.googleusercontent.com/a-/ALV-U...,"Disuruh masukan kode negara, +62 INDONESIA tid...",1,0,None,2026-04-14 01:52:53,Mhn maaf atas ketidaknyamanannya Bapak/Ibu. Pe...,2026-04-14 02:09:14,None
37,d9b74330-3946-4712-88a6-4accd6e1d076,Big Enjoy,https://play-lh.googleusercontent.com/a/ACg8oc...,kalo belum bisa pake sistem/fitur verifikasi w...,1,0,2.15.1,2026-04-14 01:19:31,Mohon maaf atas kendalanya. Untuk kendala ters...,2026-04-14 02:08:22,2.15.1
38,923ac195-829a-4516-99bf-2cb9dcd95520,Ninu Sandra,https://play-lh.googleusercontent.com/a/ACg8oc...,paling ribet,1,0,None,2026-04-13 23:39:06,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, moh...",2026-04-14 01:25:34,None
39,d5c9d7a4-f841-45ff-a436-9142952c3b02,Priyanto 67,https://play-lh.googleusercontent.com/a/ACg8oc...,lancar dan aman,5,0,2.13.0,2026-04-13 23:06:55,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 01:25:15,2.13.0
40,fa1f201c-e0e1-4884-8654-665a1a6da89c,Kamtini Kamtini,https://play-lh.googleusercontent.com/a/ACg8oc...,praktis mudah,5,0,2.15.1,2026-04-13 22:54:43,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-14 01:25:12,2.15.1
41,71ff0697-5a63-4107-bd72-612473d3c81d,Hadi K_04,https://play-lh.googleusercontent.com/a-/ALV-U...,tidak bisa buat rekening baru,2,0,None,2026-04-13 15:33:56,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2026-04-13 15:58:57,None
42,fd74bc2c-e02a-43d9-8f63-bcb5a0061776,Dede Tanuwidjaja,https://play-lh.googleusercontent.com/a/ACg8oc...,tgl 11 Apr: setelah update lemot. Saya coba sb...,5,0,2.15.1,2026-04-13 15:15:32,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-13 15:58:14,2.15.1
43,6559e9b8-924c-42e7-9e80-63e6bd5f28dd,Adjie Kyta,https://play-lh.googleusercontent.com/a/ACg8oc...,ini gmn uang saya mau bayar2 malah gk bs di bu...,1,0,2.15.1,2026-04-13 15:08:34,"Mohon maaf atas ketidaknyamanan Bapak/Ibu, unt...",2026-04-13 15:57:11,2.15.1
44,807bcb45-c92a-49a6-9211-9fc707025c03,Subur Subarkah,https://play-lh.googleusercontent.com/a-/ALV-U...,ok banget,5,0,None,2026-04-13 14:59:46,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-13 15:56:27,None
45,05f0140b-8869-4e79-8f03-e8bde3cb78db,Chandra Prima Panjaitan,https://play-lh.googleusercontent.com/a-/ALV-U...,rajin banget muncul update aplikasinya. harusn...,3,0,2.15.1,2026-04-13 14:09:38,Mohon maaf atas ketidaknyamanannya. Ulasan Bap...,2026-04-13 14:14:22,2.15.1
46,13d059f7-45a3-4a7c-b5a9-f73025ea4093,Muhammad Iqbal,https://play-lh.googleusercontent.com/a-/ALV-U...,"BCA tolong lah. lu itu perusahaan besar , suda...",1,0,2.15.1,2026-04-13 13:20:32,Mohon maaf atas ketidaknyamanannya Bapak/Ibu. ...,2026-04-13 14:07:43,2.15.1
47,049f784d-0ff7-4e3e-8671-9fb55321ba2f,siswanto,https://play-lh.googleusercontent.com/a-/ALV-U...,bar update sekarang kenceng lagi pk josss pak,5,0,2.15.1,2026-04-13 13:16:15,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-13 14:13:02,2.15.1
48,aaea8619-729c-4b8a-be9c-7d48e134c8cc,Dewi Novita,https://play-lh.googleusercontent.com/a/ACg8oc...,awalnya kesel karna susah banget buat verifika...,5,0,2.15.1,2026-04-13 12:59:14,Terima kasih atas saran dan ulasannya. Hal ini...,2026-04-13 14:06:08,2.15.1
49,ed7878cf-7457-43bb-b45c-50c63fd9ec07,Apik Kaka,https://play-lh.googleusercontent.com/a/ACg8oc...,baik,5,0,2.15.1,2026-04-13 10:35:26,Terima kasih atas ulasannya. Semoga aplikasi m...,2026-04-13 10:47:09,2.15.1

In [8]:
df['score'].value_counts()

score
5    8388
1    7261
3    1694
2    1520
4    1137
Name: count, dtype: int64

In [9]:
df.to_csv('mybca_reviews.csv', index=False)

In [10]:
!pip freeze requirements.txt

absl-py==1.4.0
accelerate==1.13.0
access==1.1.10.post3
affine==2.4.0
aiofiles==24.1.0
aiohappyeyeballs==2.6.1
aiohttp==3.13.5
aiosignal==1.4.0
aiosqlite==0.22.1
alabaster==1.0.0
albucore==0.0.24
albumentations==2.0.8
ale-py==0.11.2
alembic==1.18.4
altair==5.5.0
annotated-doc==0.0.4
annotated-types==0.7.0
antlr4-python3-runtime==4.9.3
anyio==4.13.0
anywidget==0.9.21
apsw==3.53.0.0
apswutils==0.1.2
argon2-cffi==25.1.0
argon2-cffi-bindings==25.1.0
array_record==0.8.3
arrow==1.4.0
arviz==0.22.0
astropy==7.2.0
astropy-iers-data==0.2026.4.6.0.54.57
astunparse==1.6.3
atpublic==5.1
attrs==26.1.0
audioread==3.1.0
Authlib==1.6.9
autograd==1.8.0
babel==2.18.0
backcall==0.2.0
beartype==0.22.9
beautifulsoup4==4.13.5
betterproto==2.0.0b6
bigframes==2.39.0
bigquery-magics==0.12.2
bleach==6.3.0
blinker==1.9.0
blis==1.3.3
blobfile==3.2.0
blosc2==4.1.2
bokeh==3.8.2
Bottleneck==1.4.2
bqplot==0.12.45
branca==0.8.2
brotli==1.2.0
CacheControl==0.14.4
cachetools==6.2.6
catalogue==2.0.10
certifi==2026.2.25
cffi==2.0.0
chardet==5.2.0
charset-normalizer==3.4.7
clarabel==0.11.1
click==8.3.2
click-plugins==1.1.1.2
cligj==0.7.2
cloudpathlib==0.23.0
cloudpickle==3.1.2
cmake==3.31.10
cmdstanpy==1.3.0
colorcet==3.1.0
colorlover==0.3.0
community==1.0.0b1
confection==1.3.3
cons==0.4.7
contourpy==1.3.3
cramjam==2.11.0
cryptography==43.0.3
cufflinks==0.17.3
curl_cffi==0.15.0
cvxopt==1.3.2
cvxpy==1.6.7
cycler==0.12.1
cyipopt==1.5.0
cymem==2.0.13
Cython==3.0.12
dask==2026.3.0
dataproc-spark-connect==1.1.0
datasets==4.0.0
db-dtypes==1.5.1
dbus-python==1.2.18
debugpy==1.8.15
decorator==4.4.2
defusedxml==0.7.1
deprecation==2.1.0
diffusers==0.37.1
dill==0.3.8
distro==1.9.0
dlib==19.24.6
dm-tree==0.1.10
docstring_parser==0.17.0
docutils==0.21.2
dopamine_rl==4.1.2
duckdb==1.3.2
earthengine-api==1.7.21
easydict==1.13
editdistance==0.8.1
eerepr==0.1.2
einops==0.8.2
en_core_web_sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-3.8.0/en_core_web_sm-3.8.0-py3-none-any.whl#sha256=1932429db727d4bff3deed6b34cfc05df17794f4a52eeb26cf8928f7c1a0fb85
entrypoints==0.4
esda==2.9.0
et_xmlfile==2.0.0
etils==1.14.0
etuples==0.3.10
Farama-Notifications==0.0.4
fastai==2.8.7
fastapi==0.135.3
fastcore==1.12.36
fastdownload==0.0.7
fastjsonschema==2.21.2
fastlite==0.2.4
fastprogress==1.1.5
fasttransform==0.0.2
ffmpy==1.0.0
filelock==3.25.2
fiona==1.10.1
firebase-admin==6.9.0
Flask==3.1.3
flatbuffers==25.12.19
flax==0.11.2
folium==0.20.0
fonttools==4.62.1
fqdn==1.5.1
frozendict==2.4.7
frozenlist==1.8.0
fsspec==2025.3.0
future==1.0.0
gast==0.7.0
gcsfs==2025.3.0
GDAL==3.8.4
gdown==5.2.1
geemap==0.37.2
geocoder==1.38.1
geographiclib==2.1
geopandas==1.1.3
geopy==2.4.1
giddy==2.3.6
gin-config==0.5.0
gitdb==4.0.12
GitPython==3.1.46
glob2==0.7
google==3.0.0
google-adk==1.29.0
google-ai-generativelanguage==0.6.15
google-api-core==2.30.3
google-api-python-client==2.194.0
google-auth==2.47.0
google-auth-httplib2==0.3.1
google-auth-oauthlib==1.3.1
google-cloud-aiplatform==1.147.0
google-cloud-appengine-logging==1.9.0
google-cloud-audit-log==0.5.0
google-cloud-bigquery==3.41.0
google-cloud-bigquery-connection==1.21.0
google-cloud-bigquery-storage==2.37.0
google-cloud-bigtable==2.36.0
google-cloud-core==2.5.1
google-cloud-dataplex==2.18.0
google-cloud-dataproc==5.26.0
google-cloud-datastore==2.24.0
google-cloud-discoveryengine==0.13.12
google-cloud-firestore==2.26.0
google-cloud-functions==1.23.0
google-cloud-iam==2.22.0
google-cloud-language==2.20.0
google-cloud-logging==3.15.0
google-cloud-monitoring==2.30.0
google-cloud-pubsub==2.37.0
google-cloud-resource-manager==1.17.0
google-cloud-secret-manager==2.27.0
google-cloud-spanner==3.64.0
google-cloud-speech==2.38.0
google-cloud-storage==3.10.1
google-cloud-trace==1.19.0
google-cloud-translate==3.26.0
google-colab @ file:///colabtools/dist/google_colab-1.0.0.tar.gz
google-crc32c==1.8.0
google-genai==1.68.0
google-generativeai==0.8.6
google-pasta==0.2.0
google-play-scraper==1.2.7
google-resumable-media==2.8.2
googleapis-common-protos==1.74.0
googledrivedownloader==1.1.0
gradio==5.50.0
gradio_client==1.14.0
grain==0.2.16
graphviz==0.21
greenlet==3.4.0
groovy==0.1.2
grpc-google-iam-v1==0.14.4
grpc-interceptor==0.15.4
grpcio==1.80.0
grpcio-status==1.71.2
grpclib==0.4.9
gspread==6.2.1
gspread-dataframe==4.0.0
gym==0.25.2
gym-notices==0.1.0
gymnasium==1.2.3
h11==0.16.0
h2==4.3.0
h5netcdf==1.8.1
h5py==3.16.0
hdbscan==0.8.42
hf-xet==1.4.3
highspy==1.14.0
holidays==0.94
holoviews==1.22.1
hpack==4.1.0
html5lib==1.1
httpcore==1.0.9
httpimport==1.4.1
httplib2==0.31.2
httptools==0.7.1
httpx==0.28.1
httpx-sse==0.4.3
huggingface_hub==1.10.1
humanize==4.15.0
hyperframe==6.1.0
hyperopt==0.2.7
ibis-framework==9.5.0
idna==3.11
ImageIO==2.37.3
imageio-ffmpeg==0.6.0
imagesize==2.0.0
imbalanced-learn==0.14.1
immutabledict==4.3.1
importlib_metadata==8.7.1
importlib_resources==6.5.2
imutils==0.5.4
inequality==1.1.2
inflect==7.5.0
iniconfig==2.3.0
intel-cmplr-lib-ur==2025.3.3
intel-openmp==2025.3.3
ipyevents==2.0.4
ipyfilechooser==0.6.0
ipykernel==6.17.1
ipyleaflet==0.20.0
ipyparallel==8.8.0
ipython==7.34.0
ipython-genutils==0.2.0
ipython-sql==0.5.0
ipywidgets==7.7.1
isoduration==20.11.0
itsdangerous==2.2.0
jaraco.classes==3.4.0
jaraco.context==6.1.2
jaraco.functools==4.4.0
jax==0.7.2
jaxlib==0.7.2
jeepney==0.9.0
jieba==0.42.1
Jinja2==3.1.6
jiter==0.14.0
joblib==1.5.3
jsonpatch==1.33
jsonpickle==4.1.1
jsonpointer==3.1.1
jsonschema==4.26.0
jsonschema-specifications==2025.9.1
jupyter-console==6.6.3
jupyter-events==0.12.0
jupyter-leaflet==0.20.0
jupyter_client==7.4.9
jupyter_core==5.9.1
jupyter_kernel_gateway @ git+https://github.com/googlecolab/kernel_gateway@b134e9945df25c2dcb98ade9129399be10788671
jupyter_server==2.14.0
jupyter_server_terminals==0.5.4
jupyterlab_pygments==0.3.0
jupyterlab_widgets==3.0.16
jupytext==1.19.1
kaggle==2.0.1
kagglehub==1.0.0
kagglesdk==0.1.18
keras==3.13.2
keras-hub==0.26.0
keras-nlp==0.26.0
keyring==25.7.0
keyrings.google-artifactregistry-auth==1.1.2
kiwisolver==1.5.0
langchain==1.2.15
langchain-core==1.2.28
langgraph==1.1.6
langgraph-checkpoint==4.0.1
langgraph-prebuilt==1.0.9
langgraph-sdk==0.3.13
langsmith==0.7.30
lark==1.3.1
launchpadlib==1.10.16
lazr.restfulclient==0.14.4
lazr.uri==1.0.6
lazy-loader==0.5
libclang==18.1.1
libpysal==4.14.1
librosa==0.11.0
lightgbm==4.6.0
linkify-it-py==2.1.0
llvmlite==0.43.0
locket==1.0.0
logical-unification==0.4.7
lxml==6.0.3
Mako==1.3.10
mapclassify==2.10.0
Markdown==3.10.2
markdown-it-py==4.0.0
MarkupSafe==3.0.3
matplotlib==3.10.0
matplotlib-inline==0.2.1
matplotlib-venn==1.1.2
mcp==1.27.0
mdit-py-plugins==0.5.0
mdurl==0.1.2
mgwr==2.2.1
miniKanren==1.0.5
missingno==0.5.2
mistune==3.2.0
mizani==0.13.5
mkl==2025.3.1
ml_dtypes==0.5.4
mlxtend==0.23.4
mmh3==5.2.1
momepy==0.11.0
more-itertools==10.8.0
moviepy==1.0.3
mpmath==1.3.0
msgpack==1.1.2
multidict==6.7.1
multipledispatch==1.0.0
multiprocess==0.70.16
multitasking==0.0.12
murmurhash==1.0.15
music21==9.9.1
namex==0.1.0
narwhals==2.19.0
natsort==8.4.0
nbclassic==1.3.3
nbclient==0.10.4
nbconvert==7.17.1
nbformat==5.10.4
ndindex==1.10.1
nest-asyncio==1.6.0
networkx==3.6.1
nibabel==5.4.2
nltk==3.9.1
notebook==6.5.7
notebook_shim==0.2.4
numba==0.60.0
numexpr==2.14.1
numpy==2.0.2
nvidia-nccl-cu12==2.29.7
oauth2client==4.1.3
oauthlib==3.3.1
omegaconf==2.3.0
onemkl-license==2025.3.1
openai==2.31.0
opencv-contrib-python==4.13.0.92
opencv-python==4.13.0.92
opencv-python-headless==4.13.0.92
openpyxl==3.1.5
opentelemetry-api==1.38.0
opentelemetry-exporter-gcp-logging==1.11.0a0
opentelemetry-exporter-gcp-monitoring==1.11.0a0
opentelemetry-exporter-gcp-trace==1.11.0
opentelemetry-exporter-otlp-proto-common==1.38.0
opentelemetry-exporter-otlp-proto-http==1.38.0
opentelemetry-proto==1.38.0
opentelemetry-resourcedetector-gcp==1.11.0a0
opentelemetry-sdk==1.38.0
opentelemetry-semantic-conventions==0.59b0
opt_einsum==3.4.0
optax==0.2.8
optree==0.19.0
orbax-checkpoint==0.11.34
orjson==3.11.8
ormsgpack==1.12.2
osqp==1.1.1
overrides==7.7.0
packaging==26.0
pandas==2.2.2
pandas-datareader==0.10.0
pandas-gbq==0.30.0
pandas-stubs==2.2.2.240909
pandocfilters==1.5.1
panel==1.8.10
param==2.3.3
parso==0.8.6
parsy==2.2
partd==1.4.2
patsy==1.0.2
peewee==4.0.4
peft==0.18.1
pexpect==4.9.0
pickleshare==0.7.5
pillow==11.3.0
platformdirs==4.9.6
plotly==5.24.1
plotnine==0.14.5
pluggy==1.6.0
plum-dispatch==2.8.0
pointpats==2.5.5
polars==1.35.2
polars-runtime-32==1.35.2
pooch==1.9.0
portpicker==1.5.2
preshed==3.0.13
prettytable==3.17.0
proglog==0.1.12
progressbar2==4.5.0
prometheus_client==0.25.0
promise==2.3
prompt_toolkit==3.0.52
propcache==0.4.1
prophet==1.3.0
proto-plus==1.27.2
protobuf==5.29.6
psutil==5.9.5
psycopg2==2.9.11
psygnal==0.15.1
ptyprocess==0.7.0
PuLP==3.3.0
py-cpuinfo==9.0.0
py4j==0.10.9.9
pyarrow==18.1.0
pyasn1==0.6.3
pyasn1_modules==0.4.2
pycairo==1.29.0
pycocotools==2.0.11
pycparser==3.0
pycryptodomex==3.23.0
pydantic==2.12.3
pydantic-settings==2.13.1
pydantic_core==2.41.4
pydata-google-auth==1.9.1
pydot==4.0.1
pydotplus==2.0.2
PyDrive2==1.21.3
pydub==0.25.1
pyerfa==2.0.1.5
pygame==2.6.1
pygit2==1.19.2
Pygments==2.20.0
PyGObject==3.48.2
pyiceberg==0.11.1
PyJWT==2.12.1
pymc==5.28.4
pynndescent==0.6.0
pyogrio==0.12.1
pyomo==6.10.0
PyOpenGL==3.1.10
pyOpenSSL==24.2.1
pyparsing==3.3.2
pyperclip==1.11.0
pyproj==3.7.2
pyroaring==1.0.4
pysal==25.7
pyshp==3.0.3
PySocks==1.7.1
pyspark==4.0.2
pytensor==2.38.2
pytest==8.4.2
python-apt==0.0.0
python-box==7.4.1
python-dateutil==2.9.0.post0
python-dotenv==1.2.2
python-fasthtml==0.12.50
python-json-logger==4.1.0
python-louvain==0.16
python-multipart==0.0.26
python-slugify==8.0.4
python-snappy==0.7.3
python-utils==3.9.1
pytz==2025.2
pyviz_comms==3.0.6
PyWavelets==1.9.0
PyYAML==6.0.3
pyzmq==26.2.1
quantecon==0.11.2
rasterio==1.5.0
rasterstats==0.20.0
ratelim==0.1.6
referencing==0.37.0
regex==2025.11.3
requests==2.32.4
requests-oauthlib==2.0.0
requests-toolbelt==1.0.0
requirements-parser==0.9.0
rfc3339-validator==0.1.4
rfc3986-validator==0.1.1
rfc3987-syntax==1.1.0
rich==13.9.4
roman-numerals==4.1.0
roman-numerals-py==4.1.0
rpds-py==0.30.0
rpy2==3.5.17
rsa==4.9.1
rtree==1.4.1
ruff==0.15.10
safehttpx==0.1.7
safetensors==0.7.0
scikit-image==0.25.2
scikit-learn==1.6.1
scipy==1.16.3
scooby==0.11.0
scs==3.2.11
seaborn==0.13.2
SecretStorage==3.5.0
segregation==2.5.4
semantic-version==2.10.0
Send2Trash==2.1.0
sentence-transformers==5.4.0
sentencepiece==0.2.1
sentry-sdk==2.57.0
setuptools==75.2.0
shap==0.51.0
shapely==2.1.2
shellingham==1.5.4
simple-parsing==0.1.8
simplejson==3.20.2
simsimd==6.5.16
six==1.17.0
sklearn-compat==0.1.5
sklearn-pandas==2.2.0
slicer==0.0.8
smart_open==7.5.1
smmap==5.0.3
sniffio==1.3.1
snowballstemmer==3.0.1
soundfile==0.13.1
soupsieve==2.8.3
soxr==1.0.0
spacy==3.8.14
spacy-legacy==3.0.12
spacy-loggers==1.0.5
spaghetti==1.7.6
spanner-graph-notebook==1.1.8
spglm==1.1.0
Sphinx==8.2.3
sphinxcontrib-applehelp==2.0.0
sphinxcontrib-devhelp==2.0.0
sphinxcontrib-htmlhelp==2.1.0
sphinxcontrib-jsmath==1.0.1
sphinxcontrib-qthelp==2.0.0
sphinxcontrib-serializinghtml==2.0.0
spint==1.0.7
splot==1.1.7
spopt==0.7.0
spreg==1.9.0
SQLAlchemy==2.0.49
sqlalchemy-spanner==1.17.3
sqlglot==25.20.2
sqlparse==0.5.5
srsly==2.5.3
sse-starlette==3.3.4
stanio==0.5.1
starlette==0.52.1
statsmodels==0.14.6
strictyaml==1.7.3
stringzilla==4.6.0
stumpy==1.13.0
sympy==1.14.0
tables==3.10.2
tabulate==0.9.0
tbb==2022.3.1
tcmlib==1.4.1
tenacity==9.1.4
tensorboard==2.19.0
tensorboard-data-server==0.7.2
tensorflow==2.19.0
tensorflow-datasets==4.9.9
tensorflow-hub==0.16.1
tensorflow-metadata==1.17.3
tensorflow-probability==0.25.0
tensorflow-text==2.19.0
tensorflow_decision_forests==1.12.0
tensorstore==0.1.82
termcolor==3.3.0
terminado==0.18.1
text-unidecode==1.3
textblob==0.19.0
tf-slim==1.1.0
tf_keras==2.19.0
thinc==8.3.13
threadpoolctl==3.6.0
tifffile==2026.3.3
tiktoken==0.12.0
timm==1.0.26
tinycss2==1.4.0
tobler==0.14.0
tokenizers==0.22.2
toml==0.10.2
tomlkit==0.13.3
toolz==0.12.1
torch @ https://download.pytorch.org/whl/cpu/torch-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl
torchao==0.10.0
torchaudio @ https://download.pytorch.org/whl/cpu/torchaudio-2.10.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl
torchcodec @ https://download.pytorch.org/whl/cpu/torchcodec-0.10.0-cp312-cp312-manylinux_2_28_x86_64.whl
torchdata==0.11.0
torchsummary==1.5.1
torchtune==0.6.1
torchvision @ https://download.pytorch.org/whl/cpu/torchvision-0.25.0%2Bcpu-cp312-cp312-manylinux_2_28_x86_64.whl
tornado==6.5.1
tqdm==4.67.3
traitlets==5.7.1
traittypes==0.2.3
transformers==5.0.0
treescope==0.1.10
tsfresh==0.21.1
tweepy==4.16.0
typeguard==4.5.1
typer==0.24.1
typer-slim==0.24.0
types-pytz==2026.1.1.20260408
types-setuptools==82.0.0.20260402
typing-inspection==0.4.2
typing_extensions==4.15.0
tzdata==2026.1
tzlocal==5.3.1
uc-micro-py==2.0.0
umap-learn==0.5.12
umf==1.0.3
uri-template==1.3.0
uritemplate==4.2.0
urllib3==2.5.0
uuid_utils==0.14.1
uvicorn==0.44.0
uvloop==0.22.1
vega-datasets==0.9.0
wadllib==1.3.6
wandb==0.25.1
wasabi==1.1.3
watchdog==6.0.0
watchfiles==1.1.1
wcwidth==0.6.0
weasel==1.0.0
webcolors==25.10.0
webencodings==0.5.1
websocket-client==1.9.0
websockets==15.0.1
Werkzeug==3.1.8
wheel==0.46.3
widgetsnbextension==3.6.10
wordcloud==1.9.6
wrapt==2.1.2
wurlitzer==3.1.1
xarray==2025.12.0
xarray-einstats==0.10.0
xgboost==3.2.0
xlrd==2.0.2
xxhash==3.6.0
xyzservices==2026.3.0
yarl==1.23.0
ydf==0.15.0
yellowbrick==1.5
yfinance==0.2.66
zipp==3.23.0
zstandard==0.25.0

In [11]:
pip freeze > requirements.txt